import React from "react";

export default function Agreement(){
    const linkStyle = "text-blue-600 hover:text-teal-800 underline font-medium transition duration-200";
    return(
        <div className="bg-white font-sans min-h-screen justify-center ">
             
      <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
       <span><a href="mailto:remitly-security@hotmail.com" target="_blank" rel="noreferrer" className={linkStyle}> Print and/or download pdf</a>
                      <h1 id="transaction-and-account-security" className="text-3xl sm:text-4xl font-extrabold text-gray-900 mb-6">
          Vneed Pay User Agreement
        </h1> 
       
<p>This User Agreement ( <strong>"Agreement"</strong> ) is effective as of  <strong>March 1, 2016</strong> , and was most recently updated on  <strong>August 26, 2021</strong>. It describes the terms by which you will be bound when you use the services accessible at <a class="f11qm70v" href="https://www.remitly.com/" target="_blank" rel="noreferrer">www.VneedPay.com</a> ( <strong>"Service"</strong> ). Do not use the Service if you do not agree to be bound by these terms. By using the Service you agree to all of the terms contained in this User Agreement.</p>
<p>As used throughout this Agreement, the terms  <strong>"Vneed Pay"</strong> ,  <strong>"we"</strong> ,  <strong>"us"</strong> , and  <strong>"our"</strong>  refer to Vneed Pay Canada, Inc., a British Columbia corporation, together with its employees, directors, successors, and assignees. The terms  <strong>"you"</strong>  and  <strong>"your"</strong>  refer to users of the Service, whether as Senders or Recipients.</p>
<p><strong>1. THE SERVICE</strong></p>
<p>The Service allows users to send international money transfers from Canada to other countries served by Vneed Pay. A  <strong>"Sender"</strong>  uses the Service to send money and a  <strong>"Recipient"</strong>  receives money through the Service. A  <strong>"Transaction"</strong>  refers to an order to send money through the Service. The  <strong>"Transaction Amount"</strong>  is the amount in Canadian dollars that the Sender provides to Vneed Pay for transmittal to the Recipient. The  <strong>"Payout Amount"</strong>  is the amount paid out to the Recipient.</p>
<p><strong>2. ELIGIBILITY FOR THE SERVICE</strong></p>
<ol>
<li><strong>Age and Capacity.</strong>  You must be at least eighteen (18) years old and have the capacity to enter into a legally binding agreement under applicable law in order to access or use the Service as a Sender. You must use the Service in your individual capacity and not on behalf of a business or legal entity. Other restrictions may apply.</li>
<li><strong>Others.</strong>  You may not submit or receive a Transaction on behalf of any other person.</li>
<li><strong>Residence within Canada.</strong>  The Service is not currently available to residents of certain provinces of Canada. Please check our website frequently to see whether your province of residence has been added to the list of eligible jurisdictions.</li>
<li><strong>Offer and Acceptance.</strong>  If you submit a Transaction, you are requesting that we process your Transaction, an offer that we may accept or reject at our sole discretion.</li>
</ol>
<p><strong>3. PAYING FOR THE SERVICE</strong></p>
<ol>
<li><strong>Charges.</strong>  With each Transaction you submit you are agreeing to pay us a service fee ( <strong>"Service Fee"</strong> ), in addition to the Transaction Amount.</li>
</ol>
<p>Payment in Canadian dollars is due at the time the Transaction is submitted for processing. If you submit a Transaction that results in us being charged NSF fees, chargeback fees, or other similar costs, you agree to reimburse Vneed Pay for all such fees.</p>
<ol>
<li><strong>Payment.</strong>  In order for us to process your Transaction you authorize us to charge any of the payment instruments included in your payment profile ( <strong>"Payment Instrument"</strong>  includes credit card, debit card, or bank account). If your payment fails you authorize us to re-try one or more times using the same Payment Instrument. You warrant that you are an authorized and lawful user of the Payment Instrument(s).</li>
<li><strong>Other Charges.</strong>  We are not responsible for fees that may be imposed by financial institutions associated with your Payment Instruments. For example, some credit card issuers may treat the use of your credit card to use the Service as a  <strong>"cash advance"</strong>  and may impose additional fees and interest cost for the Transaction. Vneed Pay is not responsible for any NSF fees, chargeback fees, or other, similar charges that might be imposed on you by your bank, credit card issuer, or other provider.</li>
</ol>
<p><strong>4. PRE-AUTHORIZED DEBIT AUTHORIZATION</strong></p>
<ol>
<li><strong>Pre-Authorized Debit.</strong>  By entering your Payment Instrument into your account's payment profile, you authorize us to begin debiting your Payment Instrument for charges with respect to your use of the Service ( <strong>"PAD"</strong> ).</li>
</ol>
<p>This PAD authorization ( <strong>"Authorization"</strong> ) constitutes your agreement and authorization for Vneed Pay to debit your Payment Instrument and is effective as of the date you provide Vneed Pay with your Payment Instrument information. You acknowledge that this is a Personal PAD drawn for the payment of goods or services related to your personal, household or consumer activity. You warrant to us on a continuing basis that all persons whose consent to debit the Payment Instrument agree to the terms of this Agreement and that the Payment Instrument information provided by you is accurate and complete. This authorization shall apply to any Payment Instrument entered into your payment profile.</p>
<ol>
<li><strong>Debit of Payment Instrument.</strong>  You acknowledge that this authorization is provided for the benefit of Vneed Pay and your financial institution ( <strong>"Financial Institution"</strong> ) and is provided in consideration of your Financial Institution agreeing to process all debits against your Payment Instrument in accordance with the Rules of the Canadian Payments Association. This authorization applies only to the method of payment and does not otherwise affect your obligations to us under this Agreement or related agreements.</li>
<li><strong>Authorization and Waiver of Pre-Notification.</strong>  You authorize us to debit your Payment Instrument for all amounts owed to us from time to time for your use of the Service, including the Transaction Amount and any Service Fees. AS THE PAYMENT AMOUNT FOR THE SERVICE IS VARIABLE, YOU WAIVE ANY REQUIREMENT THAT WE GIVE PRE-NOTIFICATION OF ANY PAYMENT AMOUNT, THE DATES ON WHICH THE DEBITS WILL BE PROCESSED, AS WELL AS NOTICE OF ANY FUTURE CHANGES TO THE AMOUNTS OR PAYMENT DATES.</li>
<li><strong>Cancellation.</strong>  You may cancel this authorization at any time by closing your Vneed Pay account. For more information on your rights to cancel a PAD agreement, you may contact your Financial Institution or visit <a class="f11qm70v" href="https://www.cdnpay.ca/" target="_blank" rel="noreferrer">www.cdnpay.ca</a>. Cancellation of this authorization does not terminate this Agreement or relieve you of any obligation to pay all amounts owing to us by a method of payment satisfactory to us.</li>
<li><strong>Delivery.</strong>  You acknowledge that providing this authorization to us constitutes delivery by you of this authorization to your Financial Institution. You acknowledge that your Financial Institution is not required to verify that each PAD submitted by us has been issued in accordance with this authorization, including, but not limited to, the amount, or that the purpose of payment for which the PAD was submitted has been fulfilled by us as a condition of honouring the PAD against your Payment Instrument. You agree to receive confirmation of this PAD authorization by email.</li>
<li><strong>Recourse.</strong>  You have certain recourse rights if any debit does not comply with this Agreement or is not authorized by you. In order to be reimbursed, you acknowledge that a declaration must be completed and presented to your Financial Institution issuing the Payment Instrument within 90 days after the date on which the PAD in dispute was posted to the Payment Instrument.</li>
</ol>
<p>You acknowledge that after 90 days, a claim that any dispute of a PAD is a matter to be resolved solely between you and Vneed Pay. To obtain more information on your recourse rights, you may contact your Financial Institution or visit <a class="f11qm70v" href="https://www.cdnpay.ca/" target="_blank" rel="noreferrer">www.cdnpay.ca</a>.</p>
<p><strong>5. RECEIVING A REMITTANCE</strong></p>
<ol>
<li><strong>Service Providers.</strong>  We work with local banks and other third party outlets (each, a  <strong>"Service Provider"</strong> ) to make funds available to Recipients. As a Sender, you are appointing your Recipient as your agent for the purpose of receiving funds transmitted through the Service. We try to provide current information on our website about the location, availability, and hours of our Service Providers. However, we are not responsible for any inaccurate or incomplete information that may be posted on the website.</li>
<li><strong>Verification.</strong>  Recipients will be required to prove their identities before receiving funds by presenting valid identification. Also, Recipients may be required to provide a reference number or another similar identifier associated with their Transactions.</li>
</ol>
<p><strong>6. IMPORTANT SERVICE RESTRICTIONS</strong></p>
<ol>
<li><strong>General.</strong>  We may refuse any Transaction or limit the amount to be transferred, either on a per Transaction or aggregated basis. These limits may be imposed on individual accounts or linked accounts. We reserve the right at any time to modify or discontinue all or any part of the Service.</li>
<li><strong>Delays.</strong>  Your Transaction may be delayed by our effort to verify your identity and validate your Payment Instruments and otherwise comply with laws or manage our financial risk. You may be entitled to a refund in certain circumstances and you may cancel your Transaction at any time while it is pending.</li>
<li><strong>Commercial Transactions.</strong>  You should not use the Service to send money except to people that you know. We are not responsible for, the quality or delivery of goods or services that you pay for using the Service. You accept that using the Service to pay for goods and services is at your own risk.</li>
<li><strong>Unauthorized Transactions.</strong>  You may not use the Service in violation of this User Agreement or applicable laws, rules or regulations. It is a violation of the User Agreement to use the Service for any of the following: sexually-oriented materials or services,  <strong>gambling activities</strong> , fraud, money-laundering, the funding of terrorist organizations, or the purchase or sale of tobacco, tobacco related paraphernalia, firearms, prescription drugs, or other controlled substances; or to send money to a Recipient that has violated the User Agreement. If you use the Service in connection with illegal conduct, Vneed Pay will report you to law enforcement. We recommend you use the Service to send money to friends and family and, therefore, you should not use the Service to send money to strangers.</li>
<li><strong>Ineligibility.</strong>  Your Payment Instrument must be issued by a Canadian financial institution. We may refuse Transactions from certain Senders and to certain Recipients that are included on the Specially Designated Persons list, Non-cooperative Countries and Territories list, and such other lists as issued by different government agencies.</li>
<li><strong>No Changes.</strong>  We generally do not let you change the details of your Transaction once it has been submitted to us for processing. It is your responsibility to make sure your Transaction details are accurate.</li>
<li><strong>Restricted Activities.</strong>  In connection with your use of our website or the Service, or in the course of your interactions with Vneed Pay, a user or a third party, you will not:</li>
<li>Breach this User Agreement, or any other agreement between you and Vneed Pay;</li>
<li>Provide false, inaccurate, or misleading information;</li>
<li>Refuse to cooperate in an investigation or provide confirmation of your identity;</li>
<li>Use an anonymizing proxy;</li>
<li>Provide yourself a cash advance from your credit card (or help others to do so);</li>
<li>Use any automatic device, or manual process to monitor or copy our website.</li>
<li><strong>Transactions to India.</strong>  Vneed Pay processes transactions to India pursuant to the Rupee Drawing Arrangements ("RDA"), as established by the Reserve Bank of India. You understand that use of the Service for commercial purposes or contributions to charitable organizations is prohibited.</li>
</ol>
<p><strong>7. HOW AND WHY WE COLLECT PERSONAL INFORMATION</strong></p>
<ol>
<li><strong>Privacy Policy.</strong>  By agreeing to this User Agreement, you acknowledge and consent to [Vneed Pay's Privacy</li>
</ol>
<p>Policy](<a class="f11qm70v" href="https://www.remitly.com/ca/en/home/policy" target="_blank" rel="noreferrer">https://www.remitly.com/ca/en/home/policy</a>.</p>
<ol>
<li><strong>Customer Identification Program.</strong>  Canadian law requires that we obtain, verify, and record information about you. We may require that you provide us with nonpublic, personal, identifying information. You authorize us to verify the information that you provide to us, including by making reference to credit report information obtained from Canadian credit reporting agencies or contacting such agencies regarding the existence or length of your credit file. We may also lawfully obtain information about you from other sources without your knowledge, including non-personal identifying information that we may obtain while you visit this website.</li>
</ol>
<p>For additional details, please see our [Privacy</p>
<p>Policy](<a class="f11qm70v" href="https://www.remitly.com/ca/en/home/policy" target="_blank" rel="noreferrer">https://www.remitly.com/ca/en/home/policy</a>.</p>
<ol>
<li><strong>Government Disclosures.</strong>  We may provide information about you and your Transactions to government authorities and law enforcement agencies, as described in our Privacy Policy.</li>
<li><strong>Verifying information.</strong>  You consent and authorize us to make any inquiries, to you or to others, which are necessary to validate the information that you provide to us. This may include asking you for additional information, requiring you to take steps to confirm ownership of your email address or financial instruments, verifying your information against third party databases, or through other sources.</li>
<li><strong>Processing of Personal Information.</strong>  Vneed Pay transfers and stores personal data in the United States and other international jurisdictions to perform its obligations and exercise its rights under the Agreement. The applicable privacy laws of those other international jurisdictions may differ from those in Canada.</li>
</ol>
<p><strong>8. ERROR RESOLUTION, CANCELLATIONS AND REFUNDS</strong></p>
<ol>
<li><strong>Error Resolution.</strong>  Let us know at any time if you have any problems with the Service. You can contact us using the contact information at the bottom of this User Agreement. For more information about  <strong>error resolution</strong>  <a class="f11qm70v" href="https://www.remitly.com/ca/en/home/errors" target="_blank" rel="noreferrer">click here</a>.</li>
<li><strong>Refunds.</strong>  You can cancel your Transaction at any time prior to its completion. Completion means that your Recipient has claimed the money you sent either through cash pick-up, home delivery or the funds have been deposited to their bank account. Upon receipt of a cancellation request, we may confirm with our Service Providers to determine whether the transaction has been completed prior to initiating a refund. The Transaction Amount will not be refunded after completion.</li>
</ol>
<p><strong>If, however, you are not satisfied with our service for any reason we will always refund the Service Fees.</strong>  All refunds will be credited to the same Payment Instrument used to pay for the Transaction. Refunds are only made in Canadian dollars and will not be adjusted to account for changes in the value of the Canadian dollar or foreign currency from the time your Transaction was submitted.</p>
<ul>
<li>If you have a complaint, first contact the consumer assistance division of  <strong>Vneed Pay Canada, Inc.</strong>  at  <strong>1-888-736-4859</strong>  (or call +1 (206) 535-6152), if you still have an unresolved complaint regarding the company's business activities, please direct your complaint to your provincial consumer affairs agency</li>
</ul>
<ol>
<li><strong>Complaints.</strong>  Although we encourage you to share with us any concerns or questions you may have about our service, including your account or a specific transaction, you may also want to contact the consumer affairs authority in your province.</li>
</ol>
<p><strong>9. INTELLECTUAL PROPERTY</strong></p>
<p>You acknowledge that the Service, including the content of this website, text, graphics, logos, and images, as well as all other Vneed Pay copyrights, trademarks, trade names, logos, and product and service names are owned exclusively by Remitly Canada, Inc. and its affiliates (the  <strong>"Remitly Intellectual Property"</strong> ). You agree not to display, use, copy, or modify Vneed Pay Intellectual Property in any manner. You are authorized solely to view and retain a copy of the pages of this website for your own personal, non-commercial use. You further agree not to: (i) use any robot, spider, scraper or other automated device to access the Service; (ii) remove or alter any copyright, trademark or other proprietary notice or legend displayed on this website (or printed pages thereof); or (iii) infringe Remitly's, its affiliates', or any third party's copyright, patent, trademark, trade secret or other intellectual property rights, or rights of publicity or privacy.</p>
<p>If you provide us with any suggestions, feedback, reviews or input ("Customer Input") related to our Services, we (and our corporate group entities) will own all right, title and interest in and to the Customer Input, even if you have designated the Customer Input as confidential. We and our corporate group entities will be entitled to use the Customer Input without restriction, including for marketing or business purposes. You assign to us all right, title and interest in and to the Customer Input and agree to provide us with any assistance we may require to document, perfect and maintain our rights in the Customer Input. For this purpose the word: "assign" is legal term which means legally transferring the benefit, such as you legally transferring the benefit of the Customer Input to us.</p>
<p><strong>10. DISCLAIMER OF WARRANTIES</strong></p>
<p>We make reasonable efforts to ensure that Transactions are processed in a timely manner, but we make no representations, warranties or conditions, express or implied, regarding the time needed to complete processing because the Service is dependent on many factors outside our control.</p>
<p>EXCEPT AS EXPRESSLY PROVIDED HEREIN, THE SERVICE IS PROVIDED TO YOU ON AN "AS IS" BASIS WITHOUT ANY WARRANTY WHATSOEVER AND Vneed Pay EXPRESSLY DISCLAIMS ALL OTHER REPRESENTATIONS, WARRANTIES, AND CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY REPRESENTATION, WARRANTY OR CONDITION OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ANY WARRANTY ARISING FROM A COURSE OF DEALING, PERFORMANCE, OR TRADE USAGE. YOUR SOLE AND EXCLUSIVE REMEDY, AND Vneed Pay'S SOLE OBLIGATION TO YOU OR ANY THIRD PARTY FOR ANY CLAIM ARISING OUT OF YOUR USE OF THE SERVICE, IS THAT YOU ARE FREE TO DISCONTINUE YOUR USE OF THE SERVICE AT ANY TIME.</p>
<p>Some jurisdictions do not allow the disclaimer of implied warranties, so the foregoing disclaimer may not apply to you. This warranty gives you specific legal rights and you may also have other legal rights that vary from province to province. In any event, you may have a right to a refund as expressly described herein.</p>
<p><strong>11. INDEMNITY</strong></p>
<p>You agree to indemnify and hold Vneed Pay, Service Providers, and their respective subsidiaries, officers, agents, partners, and employees harmless from any claim or demand, including reasonable legal fees, made by any third party due to or arising out of your use of the Service, your connection to the Service, your violation of the User Agreement, or your violation of any rights of another.</p>
<p><strong>12. LIMITATION OF LIABILITY</strong></p>
<p>IN NO EVENT SHALL Vneed Pay, SERVICE PROVIDERS, OR THEIR RESPECTIVE SUBSIDIARIES, AFFILIATES, OFFICERS, AGENTS, PARTNERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES BEYOND THE SUM OF $500.00 (IN ADDITION TO REFUNDING THE TRANSACTION AMOUNT AND SERVICE FEES), INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF Vneed Pay HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES) RESULTING FROM NEGLIGENCE ON THE PART OF REMITLY, DISBURSEMENT PARTNERS, OR THEIR RESPECTIVE SUBSIDIARIES, OFFICERS, AGENTS, PARTNERS, OR EMPLOYEES.</p>
<p>Vneed Pay SHALL NOT BE LIABLE FOR DELAYS, INTERRUPTIONS, SERVICE FAILURES, OR OTHER PROBLEMS INHERENT IN USE OF THE INTERNET, ELECTRONIC COMMUNICATIONS, TELECOMMUNICATIONS NETWORKS OR OTHER SYSTEMS OR NETWORKS OUTSIDE THE REASONABLE CONTROL OF Vneed Pay.</p>
<p><strong>13. DISPUTE RESOLUTION AND GOVERNING LAW</strong></p>
<ol>
<li><strong>Governing Law and Venue.</strong>  This User Agreement, and any dispute or claim arising out of or relating to the Service or the User Agreement (each a "Claim") shall be governed according to the laws of the Province of British Columbia and the federal laws of Canada applicable therein , except that body of law governing conflicts of law. You agree to submit to exclusive jurisdiction of the courts of competent jurisdiction in Vancouver, British Columbia. The application of the United Nations Convention on Contracts for the International Sale of Goods to this Agreement is expressly excluded.</li>
<li><strong>Disputes with Vneed Pay.</strong>  If a dispute arises between you and Vneed Pay, our goal is to learn about and address your concerns. If we are unable to address your concerns to your satisfaction, we will seek to provide you with a neutral and cost-effective means of resolving the dispute quickly.</li>
</ol>
<p>Disputes between you and Vneed Pay regarding the Service may be reported online to <a class="f11qm70v" href="https://www.remitly.com/ca/en/home/contact" target="_blank" rel="noreferrer">Customer Service</a>; by telephone at 1-888-736-4859 (or 1 (206) 535-6152); or by mail at Vneed Pay Canada, Inc., attn: Customer Service (Canada), 401 Union Street, Suite 1000, Seattle, WA 98101, USA.</p>
<ol>
<li><strong>Arbitration.</strong>  Any dispute regarding this Agreement, including the validity, existence, binding effect, interpretation, performance, breach or termination, and including tort claims, may be referred to and finally determined, to the exclusion of the courts, by a single arbitrator. The arbitration shall take place in Vancouver, British Columbia, in English, and in accordance with the [National Arbitration Rules of the National Arbitration Institute of Canada, Inc.] In all other respects the arbitration shall be governed by and subject to the Arbitration Act (RSBC).</li>
<li><strong>Improperly Filed Litigation.</strong>  All claims you bring against Vneed Pay must be resolved in accordance with section 12 of this Agreement. All claims filed or brought contrary to section 12 shall be considered improperly filed, and a breach of this Agreement. Should you file a claim contrary to section 12, Vneed Pay may recover legal fees and costs (including in-house attorneys and paralegals) up to $1,000.00 CDN, provided that Vneed Pay has notified you in writing of the improperly filed claim, and you have failed to promptly withdraw the claim.</li>
</ol>
<p><strong>14. COMMUNICATIONS</strong></p>
<p><strong>You acknowledge and consent that this User Agreement shall be entered into electronically.</strong>  Your creation of a Vneed Pay account and password constitutes an electronic signature to this User Agreement and related agreements and have the same effect as if you signed these documents in ink.</p>
<p>The following categories of information ( <strong>"Communications"</strong> ) may be provided by electronic means, subject to the requirements of Canada's Anti-Spam Laws (CASL): (i) this User Agreement and any amendments, modifications or supplements to it; (ii) your records of transactions through the Service; (iii) any initial, periodic or other disclosures or notices provided in connection with the Service, including without limitation those required by applicable law; (iv) any customer service communications, including without limitation communications with respect to claims of error or unauthorized use of the Service; (v) any other communication related to the Service or Vneed Pay.</p>
<p>Communications may be provided to you at the telephone number(s) that you provide us with through (i) the use of autodialed or prerecorded message calls or (ii) text messages, subject to the requirements of CASL. We may contact you directly or we may share your phone number with service providers with whom we contract to provide such Communications. Standard telephone minute and text charges may apply. The hardware and software requirements for access to and retention of the Communications associated with the Service include a personal computer or other device which is capable of accessing the Internet; an Internet Web Browser; and a printer or other device capable of printing and/or retaining agreements and documents.</p>
<p>The Service does not allow for Communications to be provided in paper format or through other non-electronic means. You may withdraw your consent to receive Communications electronically, but if you do, your use of the Service shall be terminated. In order to withdraw your consent, you must contact us using our contact information at the end of this User Agreement.</p>
<p><strong>15. MISCELLANEOUS</strong></p>
<ol>
<li><strong>Third party websites links and content.</strong> Any external links to third-party websites or third party content on our website are provided as a convenience to you and does not imply Vneed Pay's endorsement of the third-party website or content. These sites are not controlled by us in any way and we are not responsible for the accuracy, completeness, legality or any other aspect of these other sites including any content provided on them. You access such websites at your own risk.</li>
<li><strong>Entire Agreement.</strong>  The User Agreement constitutes the entire agreement between you and Vneed Pay and governs your use of the Service, superseding any prior agreements between you and Vneed Pay.</li>
<li><strong>No Waiver.</strong>  The failure of Vneed Pay to exercise or enforce any right or provision of the User Agreement shall not constitute a waiver of such right or provision. If any provision of the User Agreement is found by an arbitrator or court of competent jurisdiction to be invalid, the parties nevertheless agree that the arbitrator or court should endeavor to give appropriately valid effect to the intention of the User Agreement as reflected in the provision, and the other provisions of the User Agreement shall remain in full force and effect.</li>
<li><strong>Force Majeure.</strong>  We shall not be liable for any failure or delay in the performance of the Service to the extent such failure or delay is caused by matters beyond our reasonable control, including, without limitation: changes in applicable laws; closure or unavailability of required physical and network infrastructure; sovereign default; power or internet failure; civil unrest; war; and earthquake, fire, flood, or other natural disasters.</li>
<li><strong>Modification.</strong>  We may modify this User Agreement from time to time without notice to you, except as may be required by law. You can review the most current version of the User Agreement at any time by reviewing this website. You may terminate your use of the Service if you do not agree with any modification or amendment. If you use the Service after the effective date of an amendment or modification, you shall be deemed to have accepted that amendment or modification. You agree that you shall not modify this User Agreement and acknowledge that any attempts by you to modify this User Agreement shall be void.</li>
<li><strong>Transactions to Brazil.</strong> If you are sending money to Brazil in Brazilian Real using our Service and we carry out the transaction through our Brazilian licensed entity (Vneed Pay Corretora de Cambio Ltda), the terms of this <a class="f11qm70v" href="https://www.remitly.com/us/en/brazil/addendum" target="_blank" rel="noreferrer">Brazil Addendum</a> apply to your Transaction. Please read the Brazil Addendum carefully.</li>
</ol>
<p><strong>16. SECURITY</strong></p>
<p>Your security is very important to Vneed Pay, and we use a variety of security measures to make sure that your information is secure. We urge you to think carefully before sending money to anyone that you do not know well. In particular, you should be cautious of deals or offers that seem too good to be true. If you think you have been or might be a victim of fraud, please contact us immediately by telephone at 1-888-736-4859 (or +1 (206) 535-6152). If you are aware of anyone or any entity that is using the Service inappropriately, please email us at <a class="f11qm70v" href="mailto:abuse@VneedPay.com" target="_blank" rel="noreferrer">abuse@VneedPay.com</a>. If you receive any fake (phishing) emails, purporting to be from Vneed Pay, please forward them to us at <a class="f11qm70v" href="mailto:abuse@VneedPay.com" target="_blank" rel="noreferrer">abuse@VneedPay.com</a>.</p>
<p><strong>17. LANGUAGE</strong></p>
<p>This User Agreement and all related documents shall be drawn up in English only. Le présent consentement et tous les documents qui s'y rattachent soient rédigés en anglais seulement.</p>
<p><strong>18. CONTACT INFORMATION</strong></p>
<p>Questions, notifications, and requests for refunds or further information can be sent to Vneed Pay, as follows:</p>
<p><a class="f11qm70v" href="https://www.VneedPay.com/ca/en/home/contact" target="_blank" rel="noreferrer">online</a>; by telephone at 1-888-736-4859 (or +1 (206) 535-6152); or by mail at Vneed Pay Canada, Inc., attn: Customer Service (Canada), 401 Union Street, Suite 1000, Seattle, WA 98101, USA.</p>
<p>YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD THESE TERMS AND CONDITIONS AND AGREE TO BE BOUND THEREBY. YOU ACKNOWLEDGE AND AGREE THAT EACH TIME YOU SUBMIT INFORMATION OR CONDUCT ANY TRANSACTION IN CONNECTION WITH THE SERVICE, EACH SUCH TRANSACTION CONSTITUTES YOUR AGREEMENT AND INTENT TO BE BOUND BY THESE TERMS AND CONDITIONS.</p>
<p>This Agreement was last updated on April 20, 2021.</p>
</span>
      </article>
      </div>
    )

}